In [1]:
import numpy as np

## Variable Like a Tag

> 变量像个标签

In [2]:
class Variable:
    def __init__(self, data):
        self.data = data

In [3]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = Variable(data)
print(x.data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x.data = np.array(1.1)
print(x.data)

1.1
